export type Role='user'|'admin';
export type Difficulty='easy'|'medium'|'hard';
export type Category='phishing'|'vishing'|'smishing'|'pretexting'|'baiting'|'physical'|'deepfake';
export type CampaignStatus='draft'|'scheduled'|'sending'|'completed'|'cancelled';
export type RecipientStatus='pending'|'sent'|'delivered'|'opened'|'clicked'|'reported'|'submitted_data'|'failed';
export interface User{id:string;email:string;username:string;password:string;role:Role;department:string|null;is_active:number;xp:number;streak:number;last_active:string|null;created_at:string;updated_at:string;}
export type SafeUser=Omit<User,'password'>;
export interface RefreshToken{id:string;user_id:string;token_hash:string;expires_at:string;created_at:string;}
export interface ScenarioResult{id:string;user_id:string;scenario_id:number;category:Category;difficulty:Difficulty;passed:number;chosen:number;xp_earned:number;time_taken:number|null;completed_at:string;}
export interface QuizResult{id:string;user_id:string;score:number;total:number;pct:number;xp_earned:number;answers:string;completed_at:string;}
export interface ModuleProgress{id:string;user_id:string;module_id:string;completed:number;xp_earned:number;completed_at:string|null;}
export interface UserBadge{id:string;user_id:string;badge_id:string;earned_at:string;}
export interface AuditLog{id:string;user_id:string|null;action:string;detail:string|null;ip:string|null;created_at:string;}
export interface EmailTemplate{id:string;name:string;category:Category;difficulty:Difficulty;subject:string;sender_name:string;sender_email:string;html_body:string;landing_page_html:string|null;red_flags:string;created_at:string;}
export interface Campaign{id:string;name:string;template_id:string;created_by:string;status:CampaignStatus;scheduled_at:string|null;started_at:string|null;completed_at:string|null;target_department:string|null;created_at:string;}
export interface CampaignRecipient{id:string;campaign_id:string;user_id:string;status:RecipientStatus;tracking_token:string;sent_at:string|null;opened_at:string|null;clicked_at:string|null;reported_at:string|null;submitted_data_at:string|null;ip_address:string|null;user_agent:string|null;}
export interface BadgeDefinition{id:string;label:string;desc:string;icon:string;check:(s:UserStats)=>boolean;}
export interface BadgeView{id:string;label:string;desc:string;icon:string;earned:boolean;earnedAt:string|null;}
export interface UserStats{totalSims:number;streak:number;xp:number;modulesCompleted:number;phishingPassed:number;vishingPassed:number;smishingPassed:number;pretextingPassed:number;deepfakePassed:number;baitingPassed:number;physicalPassed:number;bestQuizPct:number;}
export interface JwtPayload{sub:string;email:string;role:Role;username:string;iat?:number;exp?:number;}
export interface CreateCampaignBody{name:string;templateId:string;targetDepartment?:string;targetUserIds?:string[];scheduledAt?:string;}
export interface CreateTemplateBody{name:string;category:Category;difficulty:Difficulty;subject:string;senderName:string;senderEmail:string;htmlBody:string;landingPageHtml?:string;redFlags:string[];}
export interface ScenarioResultBody{scenarioId:number;category:Category;difficulty:Difficulty;passed:boolean;chosen:number;timeTaken?:number;}
export interface QuizResultBody{score:number;total:number;answers:Array<{questionId:number;chosen:number;correct:boolean}>;}
export const XP_TABLE:Record<Difficulty,{pass:number;fail:number}>={easy:{pass:10,fail:0},medium:{pass:15,fail:0},hard:{pass:25,fail:0}};
export const MODULE_XP=20;
declare global{namespace Express{interface Request{user:JwtPayload;}}}
